### ISSUE TITLE
Clearing/resetting Picture?

### ISSUE THREAD

**Issue by garg** [Oletus/glbrush.js#25]
Is there a preferred way to clear the current Picture instead of destroying it and recreating with a new Picture and then appending it to the drawArea?

Thank you

**Comment by Oletus** [comment]
Just creating a new Picture should work, if your intention is to get rid of the undo history. There's no clean way to just clear a Picture to a color while keeping history in the current code, though that could be added pretty easily.

**Comment by garg** [comment]
Thank you! I just created a new picture and remove the old one and that cleared it.
