### ISSUE TITLE
Load brush textures asynchronously?

### ISSUE THREAD

**Issue by garg** [Oletus/glbrush.js#27]
I have an array of object literals for image brush textures. I loop to create img elements that are then pushed into a brushTextures array. That array is passed into the renderer when a picture is initialized. It appears as if they aren't loaded by the time Picture is attached, and brush events are pushed to the picture. This throws a bunch of web gl 'no image' errors in the console. 

They eventually load when I go back to my page but the first time, there is no brush output if i'm using a textureid on the brush event.

Can we add a way in the renderer to keep loading the textures even after Picture has been attached to the canvas?

**Comment by Oletus** [comment]
It's the app's responsibility to wait for textures to load first. This keeps things simple, the library doesn't need to define behavior when the texture data isn't fully loaded or what happens on a loading error.
